### ISSUE TITLE
would like to add some stack question from leetcode!

### ISSUE THREAD

**Issue by Saikat2407** [pralinkhaira1903/HacktoberFest2k23#21]
Assign this issue to me!

**Comment by Praweshkafle** [comment]
sure

**Comment by pralinkhaira1903** [comment]
Yeah simply open a pull request (PR)

**Comment by Saikat2407** [comment]
@pralinkhaira1903 hey, could you just assign this issue to me so that i could start working on it!

**Comment by pralinkhaira1903** [comment]
- Done!
- Happy Coding/Contributing :)
- Star and Share repo!!

**Comment by pralinkhaira1903** [comment]
Still you havent starred the repo!!
